name: Version
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.18.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: "chore(release): {version}"
          preset: "angular"
          tag-prefix: "v"
          output-file: "CHANGELOG.md"
          skip-version-file: "true"
          skip-on-empty: "true"
          skip-commit: "false"

      - name: Create release
        uses: actions/create-release@v1.1.4
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Discord notification
        shell: bash
        run: |
          BODY=$(jq -nc \
            --arg title "WaspLauncher Updated" \
            --arg desc "${{ github.event.head_commit.message || 'No commit message available' }}

            Download: https://github.com/WaspScripts/wasp-launcher/releases/latest" \
            --arg url  "https://github.com/WaspScripts/wasp-launcher/commit/${{ github.sha }}" \
            --arg foot "Author: ${{ github.event.head_commit.author.name }}" \
            --argjson color 16742912 \
            '{embeds:[{title:$title,description:$desc,url:$url,color:$color,footer:{text:$foot}}]}')
          curl \
              -H "Content-Type: application/json" \
              -d "$BODY" \
              ${{ secrets.UPDATES_WEBHOOK }}
